using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    [SerializeField] public GameObject player;
    private Vector3 moveTemp;

    [SerializeField] float xSpeed = 5f;
    [SerializeField] float ySpeed = 8f;
    [SerializeField] float xDifference;
    [SerializeField] float yDifference;

    [SerializeField] float movementThreshold = 2f;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {

        xDifference = player.transform.position.x >= transform.position.x ? calculateDifference(player.transform.position.x, transform.position.x) : 
                            calculateDifference(transform.position.x, player.transform.position.x);

        if (xDifference >= movementThreshold)
        {
            moveTemp.x = player.transform.position.x;
            moveTemp.z = -10;
            transform.position = Vector3.MoveTowards(transform.position, moveTemp, xSpeed * Time.deltaTime);
        }

        yDifference = player.transform.position.y >= transform.position.y ? calculateDifference(player.transform.position.y, transform.position.y) :
                            calculateDifference(transform.position.y, player.transform.position.y);
        if (yDifference >= movementThreshold)
        {
            moveTemp.y = player.transform.position.y;
            moveTemp.z = -10;
            transform.position = Vector3.MoveTowards(transform.position, moveTemp, ySpeed * Time.deltaTime);
        }

    }

    /*
        Calculate difference between two float value.
        @param val1
        First element.
        @param val2 
        Second element.
        @return val1-val2
        return the difference generated by minus val2 from val1
    */
    private float calculateDifference(float val1, float val2){
        return val1 - val2;
    }

}